max steps: 100
delta t: 30      # Minute
start t: 01/01/2020 01:00:00 AM

city:
  name: New York
  granularity: district

demand: 2020_Yellow_Taxi_Trip_Data_20250723.csv

fleet:
  size: 50
  vehicle: BYD E6
  battery model: Johnen
  depot: none

charging stations:
  - location: 208
    ports: 10
    queue: 1
    type: DC Fast Charge
