max steps: 100
delta t: 3600      # Seconds
start t: 2020/01/01 00:00:01
end t: 2025/12/31 12:59:59

city: ../data/nyc-district-map2.pkl
demand: ../data/nyc_demand.csv

fleet:
  size: 50
  vehicle: BYD E6
  battery model: multistage
  depot: none

charging stations:
  - location: 208
    max port power: 10
    max total power: 500
    efficiency: 0.9
    ports: 10
    max total power: 50
  - location: 1
    max port power: 50
    max total power: 500
    efficiency: 0.9
    ports: 10

    
